#+TITLE: Config
* Indentation
For now we set the ~tab-with~ and ~c-basic-offset~ to 4.
This is probably not the Emacs way to go. Come back to this later

#+begin_src elisp
(setq-default tab-width 4)
#+end_src

#+begin_src elisp
(setq-default c-basic-offset 4)
#+end_src

Use K&R indentation style for ~c-mode~.
#+begin_src elisp
(after! cc-mode
  (add-to-list 'c-default-style '(c-mode . "k&r")))
#+end_src

** smart-tabs-mode
#+begin_src elisp
(after! smart-tabs-mode
  (smart-tabs-insinuate 'c 'javascript)
  (setq-default indent-tabs-mode nil)

  (add-hook 'c-mode-common-hook
            (lambda () (setq indent-tabs-mode t))))
#+end_src

* UI
** Emoji
Remove the emojify global mode set by doom
#+begin_src elisp
(after! emojify
  (remove-hook 'doom-first-buffer-hook 'global-emojify-mode))
#+end_src

Use better font
#+begin_src elisp
(set-fontset-font t 'emoji '("Noto Color Emoji" . "iso10646-1") nil 'prepend)
#+end_src

** Theme
Set theme and blink modeline on bell.
#+begin_src elisp
(use-package! doom-themes
  :config
  (load-theme 'modus-vivendi t)
  (doom-themes-visual-bell-config)
  (doom-themes-org-config))
#+end_src

** Splash
Set dashboard splash to old emacs logo, because it's nicer
#+begin_src elisp
(setq
 +dashboard-banner-file (expand-file-name "splash.svg" doom-private-dir)
 +dashboard-banner-vertical-padding '(4 . 4)
 +dashboard-functions '(+dashboard-widget-banner
                             +dashboard-widget-shortmenu
                             +dashboard-widget-loaded))
#+end_src

** Font
*** Family
Doom exposes five (optional) variables for controlling fonts in Doom. Here are the three important ones:
+ ~doom-font~ doom-font
+ ~doom-variable-pitch-font~
+ ~doom-big-font~ -- used for ~doom-big-font-mode~; use this for presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or solved font string. You generally only need these two:
#+begin_src elisp
(setq doom-font (font-spec :family "Input Mono" :size 9.5 :weight 'book)
      doom-unicode-font (font-spec :family "Symbola" :size 14.0)
      doom-variable-pitch-font
      (font-spec :family "PT Sans" :size 11.0))
#+end_src

*** Truncate ellipsis
Use Unicode's ellipsis, smaller than "...".
#+begin_src elisp
(setq truncate-string-ellipsis "…")
#+end_src

*** Mixed pitch mode
Enable mixed-pitch-mode where it makes sense (LaTeX and org-mode).
We add the following fixed-faces:
- In latex, commands do not have a specific face. To set commands to fixed-pitch, instead we add rainbow-delimiters to ~mixed-pitch-fixed-pitch-faces~.
- Org-habit blocks
- Org-scheduled, to fix org-habit graph alignment somewhat
#+begin_src elisp
(use-package! mixed-pitch
  :defer t
  :config
  (set-face-attribute 'default nil :weight 'book)
  ;; This breaks font scaling. But otherwise changing fixed-pitch height doesn't work
  (setq mixed-pitch-set-height 't)
  (pushnew! mixed-pitch-fixed-pitch-faces
            ;; Fix for LaTeX where delimiters do not have a face equal to command
            'rainbow-delimiters-base-face
            'rainbow-delimiters-depth-1-face
            'rainbow-delimiters-depth-2-face
            'rainbow-delimiters-depth-3-face
            'rainbow-delimiters-depth-4-face
            'rainbow-delimiters-depth-5-face
            'rainbow-delimiters-depth-6-face
            'rainbow-delimiters-depth-7-face
            'rainbow-delimiters-depth-8-face
            'rainbow-delimiters-depth-9-face
            ;; Faces for org-habit graph
            'org-habit-alert-face
            'org-habit-alert-future-face
            'org-habit-clear-face
            'org-habit-clear-future-face
            'org-habit-overdue-face
            'org-habit-overdue-future-face
            'org-habit-ready-face
            'org-habit-ready-future-face
            ;; Fix alignment of org-habit graphs by ignoring scheduled face
            'org-scheduled
            'org-scheduled-previously
            'org-scheduled-today
            ;; Copied from doom
            'org-date
            'org-footnote
            'org-special-keyword
            'org-property-value
            'org-ref-cite-face
            'org-tag
            'org-todo-keyword-todo
            'org-todo-keyword-habt
            'org-todo-keyword-done
            'org-todo-keyword-wait
            'org-todo-keyword-kill
            'org-todo-keyword-outd
            'org-todo
            'org-done
            'font-lock-comment-face)
  :hook ((org-mode . mixed-pitch-mode)
         (TeX-mode . mixed-pitch-mode)
         (LaTeX-mode . mixed-pitch-mode)
         (org-roam-mode . mixed-pitch-mode)
         (slack-mode . mixed-pitch-mode)
         (lui-mode . mixed-pitch-mode)
         (Info-mode . mixed-pitch-mode)
         (helpful-mode . mixed-pitch-mode)
         (markdown-mode . mixed-pitch-mode)
         (gfm-mode . mixed-pitch-mode)))
#+end_src

** Line numbers
Use absolute line numbering
#+begin_src elisp
(setq display-line-numbers-type t)
#+end_src

** Line highlighting
Enable line highlighting in dired buffers, but disable it otherwise.
#+begin_src elisp
(use-package! hl-line
  :defer t
  :hook
  ((dired-after-readin . hl-line-mode)
   (org-agenda-mode . hl-line-mode))
  :init
  (remove-hook 'doom-first-buffer-hook #'global-hl-line-mode))
#+end_src

** Which-key
Replace ~evil~ and ~evil--motion~ with ~.~ and ~.m~ respectively to shorten which-key list. It would be nice to use some unicode character here, like ~ⓔ~, but this messes up which-keys columns.
#+begin_src elisp
(after! which-key
  (setq which-key-idle-delay 0.5)
  (pushnew!
   which-key-replacement-alist
   '(("" . "\\`+?evil[-:]?\\(?:a-\\)?\\(.*\\)") . (nil . ".-\\1"))
   '(("\\`g s" . "\\`evilem--?motion-\\(.*\\)") . (nil . ".m-\\1"))))
#+end_src

** Olivetti
Center the text in buffers and add a nice margin for a better reading and writing experience. Most useful in text-modes, or modes that are used for lots of reading.
#+begin_src elisp
;; (use-package! olivetti
;;   :hook ((org-mode . olivetti-mode)
;;          (markdown-mode . olivetti-mode)
;;          (TeX-mode . olivetti-mode)
;;          (LaTeX-mode . olivetti-mode)))
#+end_src

** Misc
*** Set the scroll offset
#+begin_src elisp
(setq-default scroll-margin 7)
#+end_src

*** Stripe-buffer
Stripe buffer rows where it makes sense
#+begin_src elisp
(use-package! stripe-buffer
  :defer t
  :hook ((org-mode . turn-on-stripe-table-mode)
         (dired-mode . stripe-listify-buffer)))
#+end_src

*** Indications
Indicate buffer boundaries and empty lines
#+begin_src elisp
(setq-default indicate-empty-lines t
              indicate-buffer-boundaries t)
#+end_src

*** Cursor
Enable blinking cursor
#+begin_src elisp
(blink-cursor-mode +1)
#+end_src

** Folding
#+begin_src elisp
(use-package! treesit-fold
  :defer t
  :config
  (map! :leader
        :desc "Fold"
        "z" #'treesit-fold-toggle))
#+end_src

** Embark
#+begin_src elisp
;; (use-package! embark
;;   :config
;;   (with-eval-after-load 'eglot
;;     (define-key embark-identifier-map (kbd "t") (eglot-find-typeDefinition))))
#+end_src

* Github
#+begin_src elisp
;; (use-package! consult-gh
;;   :after (consult pr-review embark)
;;   :custom
;;   (consult-gh-repo-preview-major-mode nil) ; show readmes in their original format
;;   (consult-gh-preview-major-mode 'org-mode) ; use 'org-mode for editing comments, commit messages, ...
;;   )

;; (use-package! consult-gh-with-pr-review
;;   :config
;;   (consult-gh-with-pr-review-mode +1))

;; (use-package! consult-gh-forge
;;   :config
;;   (consult-gh-forge-mode +1)
;;   (setq consult-gh-forge-timeout-seconds 20))


;; (use-package! consult-gh-transient
;;   :config
;;   (with-eval-after-load 'forge
;;     (transient-append-suffix 'forge-dispatch 'forge-add-repository
;;       '("g" "More actions (gh)" consult-gh-transient))))
#+end_src

* Evil
** Evil goggles
#+begin_src elisp
(use-package! evil-goggles
  :custom
  (evil-goggles-pulse t)
  (evil-goggles-duration 0.1)
  (evil-goggles-enable-delete t)
  (evil-goggles-enable-change t))
#+end_src
** Evil matchit
#+begin_src elisp
(use-package! evil-matchit
  :config
  (global-evil-matchit-mode 1))
#+end_src
** Escape
Bind =C-;= to escape from (almost) everywhere. ~evil-escape~ is a package that provides a function ~evil-escape~ that does exactly this. As I don't like evil-escape-key-sequences, where evil-escape is called after a quick succession of two specific keypresses, inhibit evil-escape itself.
#+begin_src elisp
(use-package! evil-escape
  :commands evil-escape
  :config
  (setq evil-escape-inhibit t)
  (global-set-key (kbd "C-;") 'evil-escape))
#+end_src
** Evil-cleverparens
Make evil work well with parenthesis/smartparens. We opt for ~evil-cleverparens~ instead of ~evil-smartparens~ because the latter has incomplete support for visual-mode yanks.
~evil-cleverparens~ is a lot more feature-rich. We don't need all this functionality, so we could look into adapting evil-smartparens to work well with visual mode yanks.
(~lispy~ + )~lispyville~ provides similar functionality, but I don't like the non-vim way of lispy-editting, (modal switches are triggered by character at point instead of key presses).
#+begin_src elisp
(use-package! evil-cleverparens
  :after (evil smartparens)
  :hook ((rust-mode rustic-mode c-mode c++-mode clojure-mode lisp-mode emacs-lisp-mode) . evil-cleverparens-mode)
  :config
  (setq evil-cleverparens-use-additional-movement-keys t))
#+end_src

As parenthesis are managed quite nicely now, we can enable smartparens-strict-mode!
#+begin_src elisp
(use-package! smartparens
  :commands (smartparens-strict-mode smartparens-mode)
  :hook ((clojure-mode . smartparens-strict-mode)
         (lisp-mode . smartparens-strict-mode)
         (emacs-lisp-mode . smartparens-strict-mode)
         (prog-mode . smartparens-mode))
  :config
  (require 'smartparens-config)
  ;; Disable single-quote auto-pairing in Rust modes to prevent 'a' lifetimes issue 
  (sp-local-pair '(rust-mode rustic-mode) "'" nil :actions nil)
  (map!
   "C-l" #'sp-forward-slurp-sexp
   "M-h" #'sp-backward-slurp-sexp
   "C-h" #'sp-forward-barf-sexp
   "M-l" #'sp-backward-barf-sexp
   ))
#+end_src

* Language Server
** LSP
#+begin_src elisp
(add-to-list 'exec-path (expand-file-name "/usr/lib/rustup/bin"))
#+end_src

** Eglot
#+begin_src elisp
(after! eglot
  (add-to-list 'eglot-ignored-server-capabilities :inlayHintProvider)
  (add-to-list 'eglot-server-programs
               `((rust-ts-mode rust-mode) . ("rust-analyzer" :initializationOptions
                                             (:procMacro (:enable t)
                                              :cargo (:buildScripts (:enable t)
                                                      :features "local-search")))))
  (add-to-list 'project-vc-extra-root-markers "Cargo.toml"))
#+end_src

Enable extensions.
#+begin_src elisp
(use-package! eglot-x
  :after eglot
  :config
      (eglot-x-setup))
#+end_src

Booster
Disabled for now because released version does not support io only mode, and emacs >30 is faster with json parsing
#+begin_src elisp
;; (use-package! eglot-booster
;;   :after eglot
;;   :config
;;   (setq eglot-booster-io-only t)
;;   (eglot-booster-mode))
#+end_src

* LaTeX
Query for master file.
#+begin_src elisp
(after! auctex
  (setq TeX-master nil))
#+end_src

#+begin_src elisp
(after! org
  ;; Tell Org Mode to use latexmk with biber
  (setq org-latex-pdf-process
        '("latexmk -f -pdf -%latex -interaction=nonstopmode -output-directory=%o %f"))
  (add-to-list 'exec-path "/usr/bin/vendor_perl")
  (setenv "PATH" (concat "/usr/bin/vendor_perl:" (getenv "PATH")))
  ;; Configure Org Mode default bibliography compiler (for newer Org versions)
  (setq org-latex-bib-compiler "biber"))
#+end_src

** Preview
Set transparent color to background for latex preview.
Scale down LaTeX previews a bit to match the used font.
#+begin_src elisp
(after! preview
  ;; This configures dynamic scaling for BOTH AUCTeX and Org-mode
  (setq preview-scale-function 'preview-scale-from-face))
#+end_src

#+begin_src elisp
(after! org
  ;; Specific only to Org-mode's traditional fallback processor
  (plist-put org-format-latex-options :scale 0.9))
#+end_src

** Fontify
#+begin_src elisp
(setq font-latex-fontify-script 'multi-level)
#+end_src
** Prettify
Add missing LaTeX prettify sequences.
#+begin_src elisp
(add-hook 'LaTeX-mode-hook
          (lambda ()
            (push '("\\lnot" . 172) prettify-symbols-alist)
            (push '("\\not \\in" . ?∉) prettify-symbols-alist)
            (push '("\\lor" . 8744) prettify-symbols-alist)
            (push '("\\land" . 8743) prettify-symbols-alist)))
#+end_src
* Org
This section implements a category-based time blocking ("time theming") system
for task management. The idea: instead of scheduling individual tasks into time
slots, you assign /categories/ (Deep Work, Admin, Comms, etc.) to blocks of
your day and work on tasks matching that category during the block.

The org files are split into =~/org/work/= and =~/org/personal/= subdirectories.
Custom agenda views show tasks grouped by category, and context switching lets
you filter to work-only, personal-only, or everything.

Expected directory structure:
#+begin_example
~/org/
  work/
    inbox.org        -- quick capture, triage later
    tasks.org        -- categorised tasks (headings: Deep Work, Admin, Comms, Meetings)
    timeblocks.org   -- scheduled time blocks with timestamps
    projects.org     -- multi-step project trees
  personal/
    inbox.org
    tasks.org
    timeblocks.org
  someday.org        -- ideas and deferred tasks
  weekly-review.org  -- datetree of weekly reviews
  templates/
    weekly-review.org -- template for the weekly review capture
#+end_example

** Directory & Files
Set ~org-directory~ before org loads (Doom requirement). All file references
derive from it so changing the base directory is a single-point change.

#+begin_src elisp
(setq org-directory "~/org/")
#+end_src

Define the file lists used by agenda, capture, and refile. Kept as =defvar= so
they can be overridden in =private.el= if needed.

#+begin_src elisp
(defvar my/work-files
  (mapcar (lambda (f) (expand-file-name f (concat org-directory "work/")))
          '("inbox.org" "tasks.org" "timeblocks.org" "projects.org"))
  "Org files for the work context.")

(defvar my/personal-files
  (mapcar (lambda (f) (expand-file-name f (concat org-directory "personal/")))
          '("inbox.org" "tasks.org" "timeblocks.org" "calendar.org"))
  "Org files for the personal context.")

(defvar my/all-files
  (append my/work-files my/personal-files)
  "All org agenda files (work + personal).")

(defun my/work-file (name)
  "Return the full path to a file in the work directory."
  (expand-file-name name (concat org-directory "work/")))

(defun my/personal-file (name)
  "Return the full path to a file in the personal directory."
  (expand-file-name name (concat org-directory "personal/")))
#+end_src

Start with all files visible in the agenda. Context switching (below) can
narrow this at runtime.

#+begin_src elisp
(setq org-agenda-files my/all-files)
#+end_src

** TODO Keywords & Tags
A single TODO sequence. ~WAITING~ logs a note on entry (the =@=) and a
timestamp on exit (the =!=). ~DONE~ and ~CANCELLED~ log timestamps.

#+begin_src elisp
(after! org
  (setq org-todo-keywords
        '((sequence
           "TODO(t)"
           "NEXT(n)"
           "WAITING(w@/!)"
           "SOMEDAY(s)"
           "|"
           "DONE(d!)"
           "CANCELLED(c@)"))))
#+end_src

Use Doom's built-in faces so keyword colours follow the active theme.

#+begin_src elisp
(after! org
  (setq org-todo-keyword-faces
        '(("TODO"      . +org-todo-todo)
          ("NEXT"      . +org-todo-active)
          ("WAITING"   . +org-todo-onhold)
          ("SOMEDAY"   . +org-todo-onhold)
          ("DONE"      . +org-todo-done)
          ("CANCELLED" . +org-todo-cancel))))
#+end_src

Tags serve double duty: the /category/ tags (mutually exclusive via
~:startgroup~) define your time-theme blocks, while /energy/ and /context/ tags
help filter during planning. Only one category and one energy level can be set
at a time.

#+begin_src elisp
(defvar my/categories
  ;;  tag          label              icon  context     key
  '(("DEEP"      "Deep Work"         "🧠"  work        ?d)
    ("ADMIN"     "Admin"             "📬"  both        ?a)
    ("COMMS"     "Comms"             "💬"  work        ?c)
    ("CREATIVE"  "Creative"          "🎨"  personal        ?r)
    ("MEETINGS"  "Meetings"          "📅"  work        ?m)
    ("REVIEW"  "Review"          "👀"  work        ?e)
    ("STORY"  "Story"          "✍🏻"  work        ?e)
    ("LEARNING"  "Learning"          "📚"  both        ?l)
    ("PERSONAL"  "Personal"          "🏠"  personal    ?p)
    ("CLEANING"  "Cleaning"          "🧹"  personal    ?C)
    ("WORKOUT"  "Workout"          "🧹"  personal    ?w)
    ("FINANCE"   "Finance"           "💰"  personal    ?f)))

;; Accessors
(defun my/cat-tag     (c) (nth 0 c))
(defun my/cat-label   (c) (nth 1 c))
(defun my/cat-icon    (c) (nth 2 c))
(defun my/cat-context (c) (nth 3 c))  ; 'work 'personal 'both
(defun my/cat-key     (c) (nth 4 c))
#+end_src

#+begin_src elisp
(defun my/categories-for-context (context)
  "Return categories matching CONTEXT ('work, 'personal, or 'both)."
  (seq-filter (lambda (c)
                (memq (my/cat-context c) `(,context both)))
              my/categories))
#+end_src

#+begin_src elisp
(defun my/make-tag-alist ()
  "Build org-tag-alist from my/categories."
  (append
   '((:startgroup . nil))
   (mapcar (lambda (c)
             (cons (my/cat-tag c) (my/cat-key c)))
           my/categories)
   '((:endgroup . nil))
   ;; Energy levels and contexts — static, not dynamic
   '((:startgroup . nil)
     ("HIGH" . ?H) ("MED" . ?M) ("LOW" . ?L)
     (:endgroup . nil)
     ("@home" . ?h) ("@office" . ?o) ("@phone" . ?n))))
#+end_src


#+begin_src elisp

(defun my/make-super-agenda-groups (context &optional order-offset)
  "Build org-super-agenda groups for CONTEXT ('work, 'personal, 'both).
Groups are ordered starting from ORDER-OFFSET (default 3, leaving
room for NEXT at 1 and habits at 2)."
  (let ((cats (if (eq context 'both)
                  my/categories
                (my/categories-for-context context)))
        (offset (or order-offset 3)))
    (seq-map-indexed
     (lambda (c i)
       (let* ((tag  (my/cat-tag c))
              (icon (my/cat-icon c))
              (label (my/cat-label c))
              (ctx  (my/cat-context c))
              (file-path (pcase ctx
                           ('work     "work")
                           ('personal "personal")
                           ('both     nil))))  ; both = no file-path filter
         (if file-path
             `(:name ,(format "%s %s" icon label)
                     :and (:tag ,tag :file-path ,file-path)
                     :order ,(+ offset i))
           `(:name ,(format "%s %s" icon label)
                   :tag ,tag
                   :order ,(+ offset i)))))
     cats)))
#+end_src


Build dynamic capture templates from the category list. Work categories get
filed under =work/tasks.org= with 1:00 effort default, personal categories
under =personal/tasks.org= with 0:30. Static templates (inboxes, someday,
weekly review, denote note) are prepended.

#+begin_src elisp
(defun my/make-capture-templates ()
  "Build org-capture-templates from my/categories."
  (let ((work-cats     (my/categories-for-context 'work))
        (personal-cats (my/categories-for-context 'personal)))
    (append
     ;; ── Static entries ──────────────────────────────────
     `(("w" "Work")
       ("wi" "Work -- Inbox" entry
        (file ,(my/work-file "inbox.org"))
        "* TODO %?\n:PROPERTIES:\n:CREATED: %U\n:END:\n%i"
        :empty-lines 1)

       ("p" "Personal")
       ("pi" "Personal -- Inbox" entry
        (file ,(my/personal-file "inbox.org"))
        "* TODO %?\n:PROPERTIES:\n:CREATED: %U\n:END:\n%i"
        :empty-lines 1)

       ("s" "Someday" entry
        (file ,(expand-file-name "someday.org" org-directory))
        "* SOMEDAY %?\n:PROPERTIES:\n:CREATED: %U\n:END:\n"
        :empty-lines 1)

       ("n" "Note (Denote)" plain
        (function denote-org-capture)
        ""
        :no-save t :immediate-finish nil :kill-buffer t :jump-to-captured t)

       ("r" "Weekly Review" entry
        (file+olp+datetree
         ,(expand-file-name "weekly-review.org" org-directory))
        (file ,(expand-file-name "templates/weekly-review.org" org-directory))
        :empty-lines 1 :tree-type week))

     ;; ── Dynamic work category templates → "w<key>" ─────
     (mapcar (lambda (c)
               `(,(concat "w" (string (my/cat-key c)))
                 ,(format "Work -- %s" (my/cat-label c))
                 entry
                 (file+olp ,(my/work-file "tasks.org")
                           ,(my/cat-label c))
                 ,(format "* TODO %%? :%s:\n:PROPERTIES:\n:Effort: 1:00\n:CREATED: %%U\n:END:\n"
                          (my/cat-tag c))
                 :empty-lines 1))
             work-cats)

     ;; ── Dynamic personal category templates → "p<key>" ──
     (mapcar (lambda (c)
               `(,(concat "p" (string (my/cat-key c)))
                 ,(format "Personal -- %s" (my/cat-label c))
                 entry
                 (file+olp ,(my/personal-file "tasks.org")
                           ,(my/cat-label c))
                 ,(format "* TODO %%? :%s:\n:PROPERTIES:\n:Effort: 0:30\n:CREATED: %%U\n:END:\n"
                          (my/cat-tag c))
                 :empty-lines 1))
             personal-cats))))
#+end_src

Build dynamic agenda commands. The super-agenda groups for each view are
generated from the category list, so adding a category to =my/categories=
automatically creates matching groups in every agenda view.

#+begin_src elisp
(defun my/make-agenda-commands ()
  "Build org-agenda-custom-commands from my/categories."
  (let* ((fixed-top    '((:name "NEXT"    :todo "NEXT"    :order 1)))
         (fixed-bottom '((:name "Habits"  :habit t        :order 96)
                          (:name "Waiting" :todo "WAITING" :order 97)
                          (:discard (:todo ("SOMEDAY" "DONE" "CANCELLED")))))
         (all-groups
          (append fixed-top
                  (my/make-super-agenda-groups 'both 3)
                  fixed-bottom))
         (work-groups
          (append fixed-top
                  (my/make-super-agenda-groups 'work 3)
                  fixed-bottom))
         (personal-groups
          (append fixed-top
                  (my/make-super-agenda-groups 'personal 3)
                  fixed-bottom))
         (time-grid-full
          '((daily today require-timed remove-match)
            (700 800 900 1000 1100 1200 1300
                 1400 1500 1600 1700 1800 1900)
            "....." "────────────────────"))
         (time-grid-week
          '((weekly today require-timed)
            (800 1000 1200 1400 1600 1800)
            "....." "────────────────────")))

    `(
      ;; ── (t) Today: work + personal integrated ────────
      ("t" "Today -- Full Day"
       ((agenda ""
                ((org-agenda-files my/all-files)
                 (org-agenda-span 'day)
                 (org-agenda-time-grid ',time-grid-full)
                 ;; Repeated scheduled items appear on the time grid, but
                 ;; org-super-agenda's `:scheduled today' matcher only checks
                 ;; the raw SCHEDULED date. Group timed blocks separately.
                 (org-super-agenda-groups
                  '((:name "Schedule & Blocks"
                     :time-grid t
                     :order 1)
                    (:name "Due Today"
                     :deadline today
                     :order 2)
                    (:name "Scheduled Today"
                     :scheduled today
                     :order 3)
                    (:discard (:anything t))))))
        (alltodo ""
                 ((org-agenda-files my/all-files)
                  (org-agenda-overriding-header "")
                  (org-super-agenda-groups ',all-groups)))))

      ;; ── (W) Week: full integrated view ───────────────
      ("W" "Week -- Full View"
       ((agenda ""
                ((org-agenda-files my/all-files)
                 (org-agenda-span 'week)
                 (org-agenda-start-on-weekday 1)
                 (org-agenda-time-grid ',time-grid-week)
                 (org-super-agenda-groups
                  '((:name "This Week"
                     :time-grid t
                     :scheduled t
                     :deadline t
                     :order 1)
                    (:discard (:anything t))))))))

      ;; ── (w) Work day only ────────────────────────────
      ("w" "Work Day"
       ((agenda ""
                ((org-agenda-files my/work-files)
                 (org-agenda-span 'day)
                 (org-agenda-time-grid ',time-grid-full)
                 (org-super-agenda-groups
                  '((:name "Work Schedule"
                     :time-grid t
                     :order 1)
                    (:name "Due Today"
                     :deadline today
                     :order 2)
                    (:name "Scheduled Today"
                     :scheduled today
                     :order 3)
                    (:discard (:anything t))))))
        (alltodo ""
                 ((org-agenda-files my/work-files)
                  (org-agenda-overriding-header "")
                  (org-super-agenda-groups ',work-groups)))))

      ;; ── (p) Personal day only ────────────────────────
      ("p" "Personal Day"
       ((agenda ""
                ((org-agenda-files my/personal-files)
                 (org-agenda-span 'day)
                 (org-agenda-time-grid ',time-grid-full)
                 (org-super-agenda-groups
                  '((:name "Personal Schedule"
                     :time-grid t
                     :order 1)
                    (:name "Due Today"
                     :deadline today
                     :order 2)
                    (:name "Scheduled Today"
                     :scheduled today
                     :order 3)
                    (:discard (:anything t))))))
        (alltodo ""
                 ((org-agenda-files my/personal-files)
                  (org-agenda-overriding-header "")
                  (org-super-agenda-groups ',personal-groups)))))

      ;; ── (R) Weekly Review ────────────────────────────
      ("R" "Weekly Review"
       ((todo "WAITING"
              ((org-agenda-files my/all-files)
               (org-agenda-overriding-header "Stuck / Waiting")))
        (todo "NEXT"
              ((org-agenda-files my/all-files)
               (org-agenda-overriding-header "Still NEXT -- carry over?")))
        (tags-todo "+DEADLINE<=\"<+7d>\""
                   ((org-agenda-files my/all-files)
                    (org-agenda-overriding-header "Due this week")))
        (todo "TODO"
              ((org-agenda-files my/all-files)
               (org-agenda-overriding-header "Full Backlog")
               (org-super-agenda-groups ',all-groups)))))

      ;; ── (H) Habits consistency view ──────────────────
      ("H" "Habits"
       ((agenda ""
                ((org-agenda-span 'day)
                 (org-habit-show-habits-only-for-today nil)
                 (org-super-agenda-groups
                  '((:name "Work Habits"     :file-path "work"     :order 1)
                    (:name "Personal Habits" :file-path "personal" :order 2)
                    (:discard (:anything t))))))))

      ;; ── (D) Deep Work session ────────────────────────
      ("D" "Deep Work Session"
       ((todo "NEXT|TODO"
              ((org-agenda-files my/work-files)
               (org-agenda-overriding-header "Deep Work -- pick your task")
               (org-super-agenda-groups
                '((:name "NEXT" :todo "NEXT" :order 1)
                  (:name "TODO" :tag "DEEP"  :order 2)
                  (:discard (:anything t))))))))

      ;; ── (A) Admin blitz ──────────────────────────────
      ("A" "Admin Blitz"
       ((todo "NEXT|TODO"
              ((org-agenda-files my/all-files)
               (org-agenda-overriding-header "Admin + Comms")
               (org-super-agenda-groups
                '((:name "NEXT"           :todo "NEXT"
                   :and (:tag ("ADMIN" "COMMS")) :order 1)
                  (:name "Work Admin"     :and (:tag "ADMIN" :file-path "work")     :order 2)
                  (:name "Work Comms"     :and (:tag "COMMS" :file-path "work")     :order 3)
                  (:name "Personal Admin" :and (:tag "ADMIN" :file-path "personal") :order 4)
                  (:discard (:anything t))))))))
      )))
#+end_src

Apply the derived configuration. Tags, capture templates, and agenda commands
are all built from =my/categories= at startup.

#+begin_src elisp
(after! org
  (setq org-tag-alist (my/make-tag-alist)))
#+end_src

Set start day to today, this was ~-3d~ by default
#+begin_src elisp
(after! org (setq org-agenda-start-day nil))
#+end_src

** Logging & Properties
Log completion timestamps into a =LOGBOOK= drawer to keep headings clean.
Both rescheduling and re-deadlining log a timestamp (no note prompt, which
would be disruptive during quick replanning).

#+begin_src elisp
(after! org
  (setq org-log-done 'time
        org-log-into-drawer t
        org-log-redeadline 'time
        org-log-reschedule 'time))
#+end_src

Effort estimates for the column view and for agenda effort sums. The list
includes common increments so you can quickly pick from the allowed values.

#+begin_src elisp
(after! org
  (setq org-global-properties
        '(("Effort_ALL" .
           "0:10 0:15 0:20 0:30 0:45 1:00 1:30 2:00 3:00 4:00"))))
#+end_src

Column view format -- shows task, state, tags, estimated effort, and clocked
time side by side. Useful for reviewing time spent vs estimated during weekly
reviews.

#+begin_src elisp
(after! org
  (setq org-columns-default-format
        "%50ITEM(Task) %TODO %TAGS %Effort(Est){:} %CLOCKSUM(Spent)"))
#+end_src

** Refile
Refile targets include all work files (2 levels deep), personal tasks (2
levels), and projects (3 levels for deeper nesting). Outline paths are shown
with the file name prefix for clarity, and you can create new parent nodes if
needed.

#+begin_src elisp
(after! org
  (setq org-refile-targets
        `((my/work-files :maxlevel . 2)
          (,(my/personal-file "tasks.org") :maxlevel . 2)
          (,(my/work-file "projects.org") :maxlevel . 3))
        org-refile-use-outline-path 'file
        org-refile-allow-creating-parent-nodes 'confirm
        org-outline-path-complete-in-steps nil))
#+end_src

Auto-save all org buffers after refile so changes are persisted immediately.
Also save before opening the agenda.

#+begin_src elisp
(after! org
  (advice-add 'org-refile :after
              (lambda (&rest _) (org-save-all-org-buffers)))
  (advice-add 'org-agenda :before
              (lambda (&rest _) (org-save-all-org-buffers))))
#+end_src

** Habits
Load ~org-habit~ and configure the graph display. The graph column is set
wide enough to not overlap with the category prefix in the agenda. Habits
live in your regular org files (any heading with =STYLE: habit= property)
-- no separate habits file needed.

#+begin_src elisp
(after! org
  (add-to-list 'org-modules 'org-habit)
  (require 'org-habit)
  (setq org-habit-show-habits-only-for-today t
        org-habit-graph-column 55
        org-habit-preceding-days 21
        org-habit-following-days 1
        org-habit-show-all-today t))
#+end_src

** General Settings
File associations -- open PDFs in Emacs (via pdf-tools), everything else as
expected.

#+begin_src elisp
(after! org
  (setq org-file-apps '((remote . emacs)
                        (auto-mode . emacs)
                        (directory . emacs)
                        ("\\.mm\\'" . default)
                        ("\\.x?html?\\'" . default)
                        ("\\.pdf\\'" . emacs))))
#+end_src

Disable line numbers in org buffers (they add visual noise to prose). Keep
compact indentation.

#+begin_src elisp
(after! org
  (setq org-indent-indentation-per-level 1)
  (add-hook 'org-mode-hook (lambda () (display-line-numbers-mode -1))))
#+end_src

Faces for agenda dates and ellipsis -- use variable pitch to match
mixed-pitch-mode.

#+begin_src elisp
(after! org
  (custom-set-faces!
    '(org-ellipsis :inherit variable-pitch)
    '(org-agenda-date :inherit variable-pitch)
    '(org-agenda-date-today :inherit variable-pitch)
    '(org-agenda-date-weekend :inherit variable-pitch)))
#+end_src

** Context Switching
Switch the active agenda scope at runtime. Useful when you want to run =M-x
org-agenda= (the full dispatcher) and only see work or personal items.

#+begin_src elisp
(defun my/context-work ()
  "Switch agenda to work files only."
  (interactive)
  (setq org-agenda-files my/work-files)
  (message "Context: WORK"))

(defun my/context-personal ()
  "Switch agenda to personal files only."
  (interactive)
  (setq org-agenda-files my/personal-files)
  (message "Context: PERSONAL"))

(defun my/context-all ()
  "Switch agenda to all files (work + personal)."
  (interactive)
  (setq org-agenda-files my/all-files)
  (message "Context: ALL"))
#+end_src

** Agenda Settings
Core agenda display settings. We keep ~org-agenda-start-with-log-mode~ from
the old config and add the time-blocking specific display options.

#+begin_src elisp
(after! org-agenda
  ;; Skip completed items everywhere
  (setq org-agenda-skip-deadline-if-done t
        org-agenda-skip-scheduled-if-done t
        org-agenda-skip-timestamp-if-done t)

  ;; Use the current repeated occurrence date for agenda display. Without
  ;; this, entries like <2026-06-06 Sat 09:45-10:00 +1d> may not appear on
  ;; today's day agenda time grid.
  (setq org-agenda-prefer-last-repeat t)

  ;; Deadline behaviour
  (setq org-deadline-warning-days 7
        org-agenda-skip-deadline-prewarning-if-scheduled t
        org-agenda-skip-scheduled-if-deadline-is-shown 'not-today)

  ;; Start week on Monday, start with log mode on
  (setq org-agenda-start-on-weekday 1
        org-agenda-start-with-log-mode t)

  ;; Visual: compact layout with a nice block separator
  (setq org-agenda-compact-blocks t
        org-agenda-block-separator
        (propertize (make-string 60 ?━) 'face 'org-agenda-structure))

  ;; Category + time prefix (wider than default for the category column)
  ;; (setq org-agenda-prefix-format
  ;;       '((agenda . " %i %┄┄┄┄┄16:c%?-12t% s")
  ;;         (todo   . " %i %┄┄┄┄┄16:c")
  ;;         (tags   . " %i %┄┄┄┄┄16:c")
  ;;         (search . " %i %┄┄┄┄┄16:c")))
  
  (setq org-agenda-prefix-format
        '((agenda . " %i %-16:c%?-12t% s")
          (todo   . " %i %-16:c")
          (tags   . " %i %-16:c")
          (search . " %i %-16:c")))
  
  ;; Tags column pushed right
  (setq org-agenda-tags-column -80)

  ;; Current time indicator and breadcrumbs
  (setq org-agenda-breadcrumbs-separator " ❱ "
        org-agenda-current-time-string "<┄┄┄┄┄┄┄┄┄┄┄┄┄┄now")
   org-agenda-prefix-format '((agenda . "%i %-12:c%?-12t%b% s")
                              (todo . " %i %-12:c")
                              (tags . " %i %-12:c")
                              (search . " %i %-12:c"))

  ;; Effort sum for appointments
  (setq org-agenda-columns-add-appointments-to-effort-sum t)

  ;; Clock report in agenda
  (setq org-agenda-clockreport-parameter-plist
        '(:link t :maxlevel 3 :compact t :narrow 55)))
#+end_src

** Super Agenda
~org-super-agenda~ groups agenda items under visual headers by category/state.
We use the ~evil-org-agenda-mode-map~ fix (not ~make-sparse-keymap~) so that
evil keybindings (j/k/etc.) work correctly on header lines.

#+begin_src elisp
(use-package! org-super-agenda
  :after org-agenda
  :config
  (org-super-agenda-mode 1)

  (custom-set-faces!
    '(org-super-agenda-header :inherit variable-pitch :height 1.5 :weight bold))

  ;; Fix evil keybindings -- org-super-agenda headers steal j/k by default
  (after! evil-org-agenda
    (setq org-super-agenda-header-map evil-org-agenda-mode-map)))
#+end_src

** Custom Agenda Views
Agenda views are generated dynamically from =my/categories=. Each view
automatically includes super-agenda groups for all defined categories.
See =my/make-agenda-commands= above for the implementation.

Available views: =t= (today), =W= (week), =w= (work day), =p= (personal day),
=R= (weekly review), =H= (habits), =D= (deep work), =A= (admin blitz).
Access via =SPC o a= prefix.

#+begin_src elisp
(after! (org-agenda org-super-agenda)
  (setq org-agenda-custom-commands (my/make-agenda-commands)))
#+end_src

** Org agenda Timeblocks
*** more readable org agendao
#+begin_src elisp
(custom-set-faces!
`(org-scheduled :foreground "#a0a0a0")
`(org-scheduled-today :foreground "#ffffff")
`(org-agenda-current-time :foreground "#ec406c" :weight bold)
`(org-agenda-calendar-event :foreground "#ffffff" :background "#264aaa")
`(org-agenda-calendar-daterange :foreground "#ffffff" :background "#264aaa")
`(org-warning :foreground "#ffffff" :background "#ac002c"))
#+end_src

*** Colourize tags
#+begin_src elisp
(after! org
  (setq org-modern-tag-faces
        '(("ADMIN"  :background "#e6f3ff" :foreground "#005a9f")
          ("MEETINGS" :background "#ffcccc" :foreground "#990000")
          ("WORKOUT"   :background "#fff0e6" :foreground "#8b4513")
          ;; Default fallback style for any tags not explicitly listed above
          (t        :background "#f0f0f0" :foreground "#333333")))
  (setq org-tag-faces
        '(("ADMIN"     . (:background "#00bfff"))
          ("MEETINGS" . (:background "#32cd32"))
          ("urgent"   . (:background "#dc143c")))))
#+end_src

** Clocking
Clock persistence survives Emacs restarts. Clocking in automatically switches
the task to =NEXT= (so your "doing now" list stays accurate), and completing a
task clocks out automatically. After 15 minutes idle, org prompts you to
resolve the idle time.

#+begin_src elisp
(after! org-clock
  (setq org-clock-persist 'history)
  (org-clock-persistence-insinuate)

  (setq org-clock-in-switch-to-state "NEXT"
        org-clock-out-when-done t
        org-clock-idle-time 15
        org-clock-mode-line-total 'today
        org-clock-report-include-clocking-task t))
#+end_src

** Capture Templates
Capture templates are generated dynamically from =my/categories=. Work
categories get =w<key>= shortcuts, personal categories get =p<key>=. Static
templates for inboxes, someday, denote notes, and weekly review are always
available. See =my/make-capture-templates= above for the implementation.

#+begin_src elisp
(after! org
  (setq org-capture-templates (my/make-capture-templates)))
#+end_src

** Org Timeblock
Visual calendar-style view of your scheduled time blocks. Complements the
text-based agenda with a graphical overview of the day. Bound to =SPC o b=.

#+begin_src elisp
(use-package! org-timeblock
  :commands (timeblock-week timeblock-day)
  :config
  (setq org-timeblock-show-future-repeats t
        org-timeblock-inbox-file (my/work-file "inbox.org"))

  (map! :map org-timeblock-mode-map
        :n "h" #'org-timeblock-day-earlier
        :n "l" #'org-timeblock-day-later
        :n "H" #'org-timeblock-backward-span
        :n "L" #'org-timeblock-forward-span

        :n "j" #'next-line
        :n "k" #'previous-line

        :n "RET" #'org-timeblock-goto
        :n "TAB" #'org-timeblock-toggle-entry

        :n "q" #'quit-window))
#+end_src

** Org QL
Power query engine for org files. Use =M-x org-ql-search= interactively to
build ad-hoc queries like =(and (todo "NEXT") (tags "DEEP"))= across your
files. Useful for searches the predefined agenda views don't cover.

#+begin_src elisp
(use-package! org-ql
  :after org)
#+end_src

** Keybindings
Agenda views and capture shortcuts replace Doom's default =SPC o a= (org-agenda
dispatcher) and =SPC o c= (org-capture dispatcher). If you need the full
dispatchers, use =M-x org-agenda= / =M-x org-capture= directly.

#+begin_src elisp
(map! :leader
      ;; Quick agenda views (replaces SPC o a -> org-agenda)
      (:prefix ("o a" . "agenda views")
       :desc "Today (all)"        "t" (cmd! (org-agenda nil "t"))
       :desc "Week (all)"         "W" (cmd! (org-agenda nil "W"))
       :desc "Work day"           "w" (cmd! (org-agenda nil "w"))
       :desc "Personal day"       "p" (cmd! (org-agenda nil "p"))
       :desc "Weekly review"      "R" (cmd! (org-agenda nil "R"))
       :desc "Habits"             "H" (cmd! (org-agenda nil "H"))
       :desc "Deep Work session"  "D" (cmd! (org-agenda nil "D"))
       :desc "Admin blitz"        "A" (cmd! (org-agenda nil "A")))

      ;; Capture shortcuts (replaces SPC o c -> org-capture)
      (:prefix ("o c" . "capture")
       :desc "Work inbox"         "w" (cmd! (org-capture nil "wi"))
       :desc "Personal inbox"     "p" (cmd! (org-capture nil "pi"))
       :desc "Someday"            "s" (cmd! (org-capture nil "s"))
       :desc "Note (Denote)"      "n" (cmd! (org-capture nil "n"))
       :desc "Weekly review"      "r" (cmd! (org-capture nil "r")))

      ;; Context switching
      (:prefix ("o s" . "agenda scope")
       :desc "All contexts"       "a" #'my/context-all
       :desc "Work only"          "w" #'my/context-work
       :desc "Personal only"      "p" #'my/context-personal)

      ;; Visual time blocks
      :desc "Visual time blocks"  "o b" #'org-timeblock)
#+end_src

Clocking keybindings in the agenda buffer (localleader prefix, so =,= in evil
normal state within the agenda).

#+begin_src elisp
(after! org-agenda
  (map! :map org-agenda-mode-map
        :localleader
        "c i" #'org-agenda-clock-in
        "c o" #'org-agenda-clock-out
        "c r" #'org-agenda-clockreport-mode
        "e"   #'org-agenda-set-effort))
#+end_src

** Roam
#+begin_src elisp
;; (use-package! org-roam
;;   :config
;;   (setq org-roam-capture-ref-templates '())
;;   (add-to-list 'org-roam-capture-ref-templates
;;                '("r" "ref" plain "%?%:initial\n"
;;                  :target (file+head "reference/%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}")
;;                  :unnarrowed t
;;                  :empty-lines 1)))
#+end_src

#+begin_src elisp
;; (use-package! websocket
;;   :after org-roam)

;; (use-package! org-roam-ui
;;   :after org
;;   ;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;   ;;         a hookable mode anymore, you're advised to pick something yourself
;;   ;;         if you don't care about startup time, use
;;   ;;  :hook (after-init . org-roam-ui-mode)
;;   :config
;;   (setq org-roam-ui-sync-theme t
;;         org-roam-ui-follow t
;;         org-roam-ui-update-on-save t
;;         org-roam-ui-open-on-start t))
#+end_src


** Org-outlook
#+begin_src elisp
;; (use-package! web-server)
#+end_src

#+begin_src elisp
;; (use-package! org-outlook
;;   :after org
;;   :config
;;   ;; Optional: Use your own Microsoft Entra App Registration
;;                                         ;(setq org-outlook-client-id "client-id-of-your-registered-app")
;;                                         ;(setq org-outlook-tenant-id "your-azure-tenant-id")

;;   ;; Required settings
;;   (setq org-outlook-gpg-recipient "luca.van.der.kamp@postnl.nl")
;;   (setq org-outlook-local-timezone "Europe/Berlin") ; Your local time zone
;;   (setq org-outlook-file "~/org/work/outlook.org")

;;   ;; Sync range (number of days)
;;   (setq org-outlook-sync-start 14)  ; days in the past to keep in sync
;;   (setq org-outlook-sync-end 90)    ; days in the future to keep in sync

;;   ;; Optional: Customize full sync frequency (default: 7 days)
;;   (setq org-outlook-full-sync-interval-days 7)  ; weekly validation
;;                                         ;(setq org-outlook-full-sync-interval-days 14) ; bi-weekly validation
;;                                         ;(setq org-outlook-full-sync-interval-days nil) ; disable automatic full syncs

;;   ;; Optional: Set your email for availability checking functions
;;   (setq org-outlook-user-email "luca.van.der.kamp@postnl.nl"))
#+end_src

** Org modern
#+begin_src elisp
(after! org
  (setq org-modern-star ["◉" "●" "○" "◈" "◆" "❖" "▶" "▷"])
  (custom-set-faces!
    '(org-modern-label nil :height 1.0 :box '(:color "#FFFFE8" :line-width 2)))
  
  (setq org-modern-timestamp nil)

  (setq org-tags-column 0
        org-auto-align-tags nil)
  
  (add-hook! 'org-agenda-finalize-hook #'org-modern-agenda))
#+end_src

** Org appear
#+begin_src elisp

(use-package! org-appear
  :after org
  :hook (org-mode . org-appear-mode)
  :config
  (setq org-appear-autoemphasis t
        org-appear-autosubmarkers t
        org-appear-autolinks nil))
#+end_src

** Org github markdown exporter
#+begin_src elisp
(use-package! ox-gfm :after org)
#+end_src

** Org capture
#+begin_src elisp
(use-package! org-protocol-capture-map :after org)
#+end_src

** Org download
#+begin_src elisp
(use-package! org-download
  :after org
  :config
  (setq-default org-download-image-dir ".attach")
  (setq org-download-method 'directory))
#+end_src

** Org popup for comment editting
#+begin_src elisp
;; (use-package! markdown-mode)
(use-package! poporg
  :commands poporg-dwim 
  :config
  (setq poporg-edit-hook '(gfm-mode))
  (setq poporg-comment-skip-regexp "[[:space:]!/]*")
  (setq markdown-fontify-code-block-default-mode 'rust-mode)
  :bind (:map rust-mode-map ("C-c \"" . poporg-dwim)))

;; From https://doc.rust-lang.org/rustdoc/documentation-tests.html#attributes
(setq rustdoc-attributes '("ignore" "should_panic" "no_run" "compile_fail" "edition2018"))

(defun mg-markdown-get-lang-mode (lang)
  (if (member lang rustdoc-attributes) 'rust-mode))
(advice-add 'markdown-get-lang-mode :before-until #'mg-markdown-get-lang-mode)
#+end_src

#+RESULTS:

** Notifications
#+begin_src elisp
;; (use-package! org-wild-notifier
;;   :hook (doom-first-input . org-wild-notifier-mode)
;;   :config
;;   (setq org-wild-notifier-alert-time '(0 10 30)))
#+end_src

** import from khal
#+begin_src elisp
(use-package! khalel
  :after org
  :config
  (khalel-add-capture-template)
  (setq khalel-capture-key "e")
  (setq khalel-import-org-file (concat org-directory "/" "personal" "/" "calendar.org"))
  (setq khalel-import-end-date "+30d"))
#+end_src

** fix ~org-tree-slide~
#+begin_src elisp
(after! org-tree-slide
  (remove-hook 'org-tree-slide-play-hook #'+org-present-hide-blocks-h)
  (remove-hook 'org-tree-slide-stop-hook #'+org-present-hide-blocks-h))
#+end_src
* Calendar

#+begin_src elisp
(after! calfw
  (advice-add #'+calendar/open-calendar :override
              (lambda ()
                (interactive)
                (calfw-open-calendar-buffer
                 :view 'week  ; Forces the calendar to open in Weekly view
                 :contents-sources
                 (list
                  ;; Work Sources
                  (calfw-org-create-file-source "Work Blocks" "~/org/work/timeblocks.org" "Tomato")
                  (calfw-org-create-file-source "Work Tasks"  "~/org/work/tasks.org"      "SteelBlue")
                  
                  ;; Personal Sources
                  (calfw-org-create-file-source "Pers Blocks" "~/org/personal/timeblocks.org" "LimeGreen")
                  (calfw-org-create-file-source "Pers Tasks"  "~/org/personal/tasks.org"      "Goldenrod"))))))
#+end_src


#+begin_src elisp
(map! :leader
      :desc "Open Custom Calendar"
      "o C" #'+calendar/open-calendar)
#+end_src

* Smerge
#+begin_src elisp
(after! smerge-mode
  (map! :leader
        :map smerge-mode-map
        :desc "Merge"
        (:prefix ("M" . "smerge")
                 "RET" #'smerge-keep-current
                 "C" #'smerge-combine-with-next
                 "E" #'smerge-ediff
                 "R" #'smerge-refine
                 "a" #'smerge-keep-all
                 "b" #'smerge-keep-base
                 "l" #'smerge-keep-lower
                 "m" #'smerge-keep-upper
                 "n" #'smerge-next
                 "o" #'smerge-keep-lower
                 "p" #'smerge-prev
                 "r" #'smerge-resolve
                 "u" #'smerge-keep-upper
                 (:prefix ("=" . "diff")
                          "<" #'smerge-diff-base-upper
                          "=" #'smerge-diff-upper-lower
                          ">" #'smerge-diff-base-lower))))
#+end_src

* Checkers
** Flycheck
#+begin_src elisp
(use-package! consult-flycheck
  :after (consult flycheck)
  :config
  (map! :leader
        "F" #'consult-flycheck))
#+end_src

The default keybindings are unbearable
#+begin_src elisp
(after! flycheck
  (map! :leader "e" flycheck-command-map))
#+end_src

#+begin_src elisp
(use-package! flyover :after flycheck)
#+end_src

#+begin_src elisp
;; (use-package! flycheck-inline
;;   :after flycheck
;;   :hook (flycheck-mode . flycheck-inline-mode))
#+End_src

** Spelling
*** Flyspell
We remove the =C-;= binding of ~flyspell-mode-keymap~ as it clashes with our binding of evil-escape.
#+begin_src elisp
(setq ispell-dictionary "en")

(defun my/sync-personal-dictionary ()
  ;; Match the current personal dictionary to the dictionary in use.
  (setq ispell-current-personal-dictionary
        (expand-file-name (concat "ispell/" ispell-current-dictionary ".pws")
                          doom-etc-dir))
  ;; For some reason, ispell also errors when the ispell-personal-dictionary does not match the current dictionary.
  (setq ispell-personal-dictionary ispell-current-personal-dictionary)
  (flyspell-buffer))

(after! ispell
  (add-hook 'ispell-change-dictionary-hook 'my/sync-personal-dictionary)
  (ispell-change-dictionary "en")
  (map! :leader
        :desc "Change dictionary language"
        "l" #'ispell-change-dictionary))

(after! flyspell
  (define-key flyspell-mode-map (kbd "C-;") nil))

#+end_src


*** langtool
#+begin_src elisp
(use-package! langtool-ignore-fonts
  :config
  (add-hook 'LaTeX-mode-hook 'langtool-ignore-fonts-minor-mode)
  (langtool-ignore-fonts-add 'latex-mode  '(font-lock-comment-face
                                            font-latex-math-face font-latex-string-face
                                            font-latex-sedate-face))
  (add-hook 'markdown-mode-hook 'langtool-ignore-fonts-minor-mode)
  (langtool-ignore-fonts-add 'markdown-mode '(markdown-code-face)))
#+end_src

*** spell-fu
#+begin_src elisp
(after! spell-fu
  (add-hook! prog-mode
    (setq spell-fu-faces-include
          '(
            ;; tree-sitter-hl-face:comment
            ;; tree-sitter-hl-face:doc
            ;; tree-sitter-hl-face:string
            ;; tree-sitter-hl-face:string.special
            font-lock-comment-face
            font-lock-doc-face
            font-lock-string-face))))
#+end_src

* Mail
#+begin_src elisp
;; (use-package! mu4e
;;   :config
;;   ;; This is set to 't' to avoid mail syncing issues when using mbsync
;;   (setq mu4e-change-filenames-when-moving t)
;;   (setq mu4e-maildir "~/mail")

;;   (setq sendmail-program (executable-find "msmtp")
;;         send-mail-function #'smtpmail-send-it
;;         message-sendmail-f-is-evil t
;;         message-sendmail-extra-arguments '("--read-envelope-from")
;;         message-send-mail-function #'message-send-mail-with-sendmail)

;;   ;; Set custom mu4e header faces
;;   (set-face-foreground 'mu4e-header-face "#CCCCB7")

;;   (defgroup my-mu4e-header-faces nil
;;     "My mu4e header faces"
;;     :prefix "mu4e-header-from-face-"
;;     :group 'tools)


;;   (defface mu4e-header-from-face
;;     '((t :foreground "black"
;;        :weight bold))
;;     "mu4e from face"
;;     :group 'my-mu4e-header-faces)

;;   (defface mu4e-header-subject-face
;;     '((t :foreground "dim gray"))
;;     "mu4e header face"
;;     :group 'my-mu4e-header-faces)

;;   (defface mu4e-header-date-face
;;     '((t :foreground "dim gray"))
;;     "mu4e date face"
;;     :group 'my-mu4e-header-faces)

;;   (defun mu4e~headers-line-apply-flag-face (msg line) line)

;;   (defun mu4e~headers-field-apply-basic-properties (msg field val width)
;;     (cl-case field
;;       (:subject
;;        (propertize
;;         (concat
;;          (mu4e~headers-thread-prefix (mu4e-message-field msg :thread))
;;          (truncate-string-to-width val 600))
;;         'face
;;         (let ((flags (mu4e-message-field msg :flags)))
;;           (cond
;;            ((memq 'trashed flags) 'mu4e-trashed-face)
;;            ((memq 'draft flags) 'mu4e-draft-face)
;;            ((or (memq 'unread flags) (memq 'new flags))
;;             'mu4e-unread-face)
;;            ((memq 'flagged flags) 'mu4e-flagged-face)
;;            ((memq 'replied flags) 'mu4e-replied-face)
;;            ((memq 'passed flags) 'mu4e-forwarded-face)
;;            (t 'mu4e-header-face)))))
;;       (:thread-subject
;;        (propertize
;;         (mu4e~headers-thread-subject msg)
;;         'face 'mu4e-header-subject-face))
;;       ((:maildir :path :message-id) val)
;;       ((:to :from :cc :bcc)
;;        (propertize
;;         (mu4e~headers-contact-str val)
;;         'face 'mu4e-header-from-face))
;;       (:from-or-to (mu4e~headers-from-or-to msg))
;;       (:date
;;        (propertize
;;         (format-time-string mu4e-headers-date-format val)
;;         'face 'mu4e-header-date-face))
;;       (:mailing-list (mu4e~headers-mailing-list val))
;;       (:human-date
;;        (propertize
;;         (mu4e~headers-human-date msg)
;;         'help-echo (format-time-string
;;                     mu4e-headers-long-date-format
;;                     (mu4e-msg-field msg :date))
;;         'face 'mu4e-header-date-face))
;;       (:flags
;;        (propertize (mu4e~headers-flags-str val)
;;                    'help-echo (format "%S" val)
;;                    'face 'font-lock-type-face))
;;       (:tags
;;        (propertize
;;         (mapconcat 'identity val ", ")
;;         'face 'font-lock-builtin-face))
;;       (:size (mu4e-display-size val))
;;       (t (mu4e~headers-custom-field msg field)))))
#+end_src

Note that the actual mail accounts are set in ~private.el~.

#+begin_src elisp
;; (use-package! mu4e-contrib)
#+end_src

** Thread folding
#+begin_src elisp
;; (use-package! mu4e-thread-folding
;;   :config
;;     ; The prefix string is displayed over the header line and it is thus recommended to have an empty field at the start of an header line. Have a look at mu4e-headers-fields.
;;   (add-to-list 'mu4e-header-info-custom
;;                '(:empty . (:name "Empty"
;;                            :shortname ""
;;                            :function (lambda (msg) "  "))))
;;   (setq mu4e-headers-fields '((:empty         .    2)
;;                               ;; (:flags         .    6)
;;                               (:from          .   22)
;;                               (:mailing-list  .   10)
;;                               (:human-date    .   12)
;;                               (:subject       .   nil))))
#+end_src

** Sync mail
Copied from [[https://tecosaur.github.io/emacs-config/config.html#fetching][tecosaurs config]].
#+begin_src elisp
(after! mu4e
  (defvar mu4e-reindex-request-file "/tmp/mu_reindex_now"
    "Location of the reindex request, signaled by existance")
  (defvar mu4e-reindex-request-min-seperation 5.0
    "Don't refresh again until this many second have elapsed.
Prevents a series of redisplays from being called (when set to an appropriate value)")

  (defvar mu4e-reindex-request--file-watcher nil)
  (defvar mu4e-reindex-request--file-just-deleted nil)
  (defvar mu4e-reindex-request--last-time 0)

  (defun mu4e-reindex-request--add-watcher ()
    (setq mu4e-reindex-request--file-just-deleted nil)
    (setq mu4e-reindex-request--file-watcher
          (file-notify-add-watch mu4e-reindex-request-file
                                 '(change)
                                 #'mu4e-file-reindex-request)))

  (defadvice! mu4e-stop-watching-for-reindex-request ()
    :after #'mu4e~proc-kill
    (if mu4e-reindex-request--file-watcher
        (file-notify-rm-watch mu4e-reindex-request--file-watcher)))

  (defadvice! mu4e-watch-for-reindex-request ()
    :after #'mu4e~proc-start
    (mu4e-stop-watching-for-reindex-request)
    (when (file-exists-p mu4e-reindex-request-file)
      (delete-file mu4e-reindex-request-file))
    (mu4e-reindex-request--add-watcher))

  (defun mu4e-file-reindex-request (event)
    "Act based on the existance of `mu4e-reindex-request-file'"
    (if mu4e-reindex-request--file-just-deleted
        (mu4e-reindex-request--add-watcher)
      (when (equal (nth 1 event) 'created)
        (delete-file mu4e-reindex-request-file)
        (setq mu4e-reindex-request--file-just-deleted t)
        (mu4e-reindex-maybe t))))

  (defun mu4e-reindex-maybe (&optional new-request)
    "Run `mu4e~proc-index' if it's been more than
`mu4e-reindex-request-min-seperation'seconds since the last request,"
    (let ((time-since-last-request (- (float-time)
                                      mu4e-reindex-request--last-time)))
      (when new-request
        (setq mu4e-reindex-request--last-time (float-time)))
      (if (> time-since-last-request mu4e-reindex-request-min-seperation)
          (mu4e~proc-index nil t)
        (when new-request
          (run-at-time (* 1.1 mu4e-reindex-request-min-seperation) nil
                       #'mu4e-reindex-maybe))))))

#+end_src

* Gnuplot
#+begin_src elisp
(use-package! gnuplot-mode)
#+end_src

* Bib
Requirements: [[https://github.com/jgm/citeproc][citeproc]]

#+begin_src elisp
(use-package! biblio)
#+end_src

#+begin_src elisp

(use-package! ebib-biblio
  :after (ebib biblio)
  :bind (:map ebib-index-mode-map
         ("B" . ebib-biblio-import-doi) ;; Press 'B' in Ebib to import by DOI
          :map biblio-selection-mode-map
          ("e" . ebib-biblio-selection-import))) ;; Press 'e' to import selected
#+end_src

#+begin_src elisp
;; Shared OA-only paper workflow for citar and ebib.
(defconst my/bib-file (expand-file-name "~/Documents/research/references.bib"))
(defconst my/bib-pdf-dir (expand-file-name "~/Documents/research/papers/"))
(defconst my/bib-notes-dir (expand-file-name "~/Documents/research/notes/"))
(use-package! citar
  :custom
  (org-cite-global-bibliography ())
  (citar-bibliography (list my/bib-file))
  (citar-library-paths (list my/bib-pdf-dir))
  (citar-notes-paths (list my/bib-notes-dir))
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  :config
  (map! :map citar-map
        :desc "Open or download PDF" "O" #'my/citar-open-or-download-pdf))

(use-package! citar-embark
  :after (citar embark)
  :config
  (citar-embark-mode +1)
  (define-key citar-embark-map (kbd "O") #'my/citar-embark-open-or-download-pdf)
  (define-key citar-embark-citation-map (kbd "O") #'my/citar-embark-open-or-download-pdf))

(use-package! ebib
  :custom
  (ebib-file-search-dirs (list my/bib-pdf-dir))
  (ebib-import-target-directory 'first-search-dir)
  (ebib-import-source-directory my/bib-pdf-dir)
  (ebib-truncate-file-names t))
#+end_src

* Vertico
#+begin_src elisp
(use-package! vertico
  :config
  (setq vertico-count 12))
#+end_src
* Languages
** Rust
*** Debugging
TODO: changed to dape
#+begin_src elisp
;; (use-package! dap-mode
;;   :config
;;   (with-eval-after-load 'lsp-rust
;;     (require 'dap-cpptools))
;;   (with-eval-after-load 'dap-cpptools
;;     ;; Add a template specific for debugging Rust programs.
;;     ;; It is used for new projects, where I can M-x dap-edit-debug-template
;;     (dap-register-debug-template "Rust::CppTools Run Configuration"
;;                                  (list :type "cppdbg"
;;                                        :request "launch"
;;                                        :name "Rust::Run"
;;                                        :MIMode "gdb"
;;                                        :miDebuggerPath "rust-gdb"
;;                                        :environment []
;;                                        :args   []
;;                                        :program "${workspaceFolder}/target/debug/libldp_dynamic_drivetimes.rlib"
;;                                        :cwd "${workspaceFolder}"
;;                                        :console "external"
;;                                        :dap-compilation "cargo build"
;;                                        :dap-compilation-dir "${workspaceFolder}")))
;;   (with-eval-after-load 'dap-mode
;;     (setq dap-default-terminal-kind "integrated")
;;     (dap-auto-configure-mode +1))
;;   )
#+end_src

*** Set backtracing
#+begin_src elisp
(use-package! rustic
  :config
  (setq rustic-compile-backtrace 1)
  (setq rustic-format-on-save t))
#+end_src

Fix a bug in rustic

#+begin_src elisp
(after! rustic
  (advice-add #'rustic-beginning-of-defun :override #'treesit-beginning-of-defun))
#+end_src

*** Separedit
#+begin_src elisp
(use-package! separedit
  :config
  (setq separedit-continue-fill-mode 't)
  (add-hook 'separedit-buffer-creation-hook #'auto-fill-mode)
  (progn
    (define-key prog-mode-map (kbd "C-c '") #'separedit)
    (setq separedit-default-mode 'markdown-mode)))
#+end_src

** Python
*** Poetry & lsp-mode
Pyright is able to work with the env of poetry when it is in the somewhere in the current project directory. Therefore, we have to set in-project virtual environments in poetry:
#+begin_src shell :tangle no
poetry config virtualenvs.in-project true
#+end_src

**** Todo it might be possible to set the environment pyright/lsp uses. Then we can stop using in-project venvs!

#+begin_src elisp
;; (use-package! poetry
;;   :config
;;   (poetry-tracking-mode)
;;   (setq poetry-tracking-strategy 'projectile)
;;   )

;; (use-package! python
;;   :mode "python-mode"
;;   :after (poetry)
;;   :hook
;;   (python-mode
;;    . (lambda () (when (poetry-venv-exist-p)
;;                   (setq-local lsp-pyls-server-command '("poetry" "run" "pyright"))
;;                   )
;;        (lsp-deferred)
;;        )
;;   )
;;   :config
;;   (setq python-indent-guess-indent-offset nil))

;; (use-package! pyvenv
;;   :hook (after-init . pyvenv-mode)
;;   )
#+end_src
*** Debugging
#+begin_src elisp
;; (use-package! dap-python
;;   :config
;;   (setq dap-python-debugger 'debugpy))
#+end_src

* Diff
#+begin_src elisp
(use-package! diff-mode
  :custom
  (diff-font-lock-prettify t)
  )
#+end_src

* Magit
Will become superflouos at Magit v4.6.0  (https://github.com/magit/magit/issues/2942#issuecomment-4200671428)
#+begin_src elisp
(after! magit
  (defun magit-diff-fontify-with-diff-mode ()
    (save-excursion
      (let ((min (point-min))
            (max (point-max)))
        (save-restriction
          (widen)
          (setq-local buffer-read-only nil)
          (setq-local diff-font-lock-syntax 'hunk-also)
          (goto-char min)
          (diff--font-lock-syntax max)))))

  (add-hook 'magit-diff-wash-diffs-hook #'magit-diff-fontify-with-diff-mode))
#+end_src

** Code review
Use passwords configured for forge.
#+begin_src elisp
(after! code-review
  (setq code-review-auth-login-marker 'forge)
  (add-hook 'code-review-mode-hook
            (lambda ()
              (persp-add-buffer (current-buffer)))))
#+end_src

#+begin_src elisp
;;; Forge interface
  (defmacro code-review-ediff-buffers (quit &rest spec)
    (declare (indent 1))
    (let ((fn (if (= (length spec) 3) 'ediff-buffers3 'ediff-buffers))
          (char ?@)
          get make kill)
      (pcase-dolist (`(,g ,m) spec)
        (let ((b (intern (format "buf%c" (cl-incf char)))))
          (push `(,b ,g) get)
          (push `(if ,b
                     (if magit-ediff-use-indirect-buffers
                         (prog1
                             (make-indirect-buffer
                              ,b (generate-new-buffer-name (buffer-name ,b)) t)
                           (setq ,b nil))
                       ,b)
                   ,m)
                make)
          (push `(unless ,b
                   (ediff-kill-buffer-carefully
                    ,(intern (format "ediff-buffer-%c" char))))
                kill)))
      (setq get  (nreverse get))
      (setq make (nreverse make))
      (setq kill (nreverse kill))
      `(let ((conf (current-window-configuration))
             ,@get)
         (,fn
          ,@make
          (list (lambda ()
                  (setq-local
                   ediff-quit-hook
                   (list ,@(and quit (list quit))
                         (lambda ()
                           ,@kill
                           (let ((magit-ediff-previous-winconf conf))
                             (run-hooks 'magit-ediff-quit-hook)))))))
          ',fn))))

  (defun code-review-ediff-compare (revA revB fileA fileB)
    "Compare REVA:FILEA with REVB:FILEB using Ediff.
FILEA and FILEB have to be relative to the top directory of the
repository.  If REVA or REVB is nil, then this stands for the
working tree state.
If the region is active, use the revisions on the first and last
line of the region.  With a prefix argument, instead of diffing
the revisions, choose a revision to view changes along, starting
at the common ancestor of both revisions (i.e., use a \"...\"
range)."
    (interactive)
    (code-review-ediff-buffers nil
                               ((if revA (magit-get-revision-buffer revA fileA) (get-file-buffer    fileA))
                                (if revA (magit-find-file-noselect  revA fileA) (find-file-noselect fileA)))
                               ((if revB (magit-get-revision-buffer revB fileB) (get-file-buffer    fileB))
                                (if revB (magit-find-file-noselect  revB fileB) (find-file-noselect fileB)))))

  (defun code-review-ediff-compare-file-at-point ()
    (interactive)
    (let* ((forge-pr
            (-first-item
             (mapcar
              (lambda (row)
                (closql--remake-instance 'forge-pullreq (forge-db) row))
              (forge-sql
               [:select $i1 :from pullreq
                :join repository :on (= repository:id pullreq:repository)
                :where (and (= repository:owner "eval-all-software")
                            (= repository:name "tempo")
                            (= pullreq:number 107))]
               (vconcat (closql--table-columns (forge-db) 'pullreq t))))))
           (default-directory "~/code/tempo"))
      (forge-checkout-pullreq forge-pr)
      (code-review-ediff-compare "main" "pr-test" "docker-compose.yml" "docker-compose.yml")))

#+end_src

#+begin_src elisp
(defun code-review-ediff-compare-file-at-point ()
  (interactive)
  (let* ((section (magit-current-section))
         (file (cond
                ((magit-file-section-p section)
                 (oref section value))
                ((magit-hunk-section-p section)
                 (alist-get 'path (oref section value)))
                (t (user-error "not in magit-section"))))
         (pr (code-review-db-get-pullreq))
         (base-upstream-branch (magit-get-upstream-branch (oref pr base-ref-name)))
         ;; assume same remote with base
         (remote (car (split-string base-upstream-branch "/"))))
    (magit-ediff-compare base-upstream-branch
                         (format "%s/%s" remote (oref pr head-ref-name))
                         file file)))

#+end_src

# * Private
# Include private config, containing things like email account configuration etc.
# #+begin_src elisp
# (load (doom-path doom-private-dir private."el"))
# #+end_src
* PR-review
#+begin_src elisp
(use-package! pr-review
  :commands (pr-review-notification)
  :bind (:map pr-review-mode-map (("RET" . pr-review-context-comment)) )
  :config
  (map! :leader
        :desc "PR notifications"
        "R" #'pr-review-notification)
  (map! :after pr-review
        :map pr-review-mode-map
        "RET" #'pr-review-context-comment
        (:prefix ("g" . "pr-review")
                 "C" #'pr-review-comment
                 "c" #'pr-review-context-comment
                 "e" #'pr-review-context-edit
                 "S" #'pr-review-submit-review
                 )))
#+end_src

* Envrc
#+begin_src elisp
;; (use-package! envrc
;;   :config
;;   (envrc-global-mode))
#+end_src
* Slack

** define function to get tokens
#+begin_src elisp
(defun my/get-slack-credentials (workspace-url)
  "Directly lookup credentials for WORKSPACE-URL (e.g., \"https://company.slack.com\")."
  (let* ((json-object-type 'hash-table)
         (json-array-type 'list)
         (json-key-type 'keyword)
         ;; Run the slacktokens command and parse output
         (data (json-read-from-string (shell-command-to-string "/home/luca/scripts/slacktokens/get_slack_tokens.py")))
         ;; 1. Extract the shared 'd' cookie
         (cookie (gethash :value (gethash :cookie data)))
         ;; 2. Direct lookup in the tokens hash-table using the URL key
         (ws-data (gethash (intern (concat ":" workspace-url)) (gethash :tokens data)))
         (token (when ws-data (gethash :token ws-data))))
    (message "Type: %s, Key: %S" (type-of (gethash :tokens data)) (gethash :tokens data))
    (message "WS Type: %s, Key: %S" (type-of ws-data) ws-data)
    (message "Token Type: %s, Key: %S" (type-of token) token)
    (if (and token cookie)
        (list token cookie)
      (error "Could not find token for %s. Ensure the URL is correct and you are logged in." workspace-url))))


(defun my/slack-refresh-team-settings (team-display-name workspace-url)
  "Refresh a specific team using its official Workspace URL."
  (cl-destructuring-bind (token cookie) (my/get-slack-credentials workspace-url)
    (slack-register-team
     :name team-display-name
     :default t
     :disable-block-format t          ; https://github.com/yuya373/emacs-slack/issues/484
     :animate-image t
     :full-and-display-names t 
     :token token
     :cookie cookie)))

(defun my/slack-auto-refresh-wrapper (&rest _)
  "Automated trigger that runs only once."
  (unless (bound-and-true-p my/slack-refreshed-p)
    (setq my/slack-refreshed-p t) ; Set flag immediately
    (condition-case err
        (my/slack-refresh-team-settings "Postnl-Engineering" "https://postnl-engineering.slack.com/")
      (error
       (setq my/slack-refreshed-p nil) ; Reset on error so you can try again
       (signal (car err) (cdr err))))))

(defun my/slack-start ()
  (interactive)
  (my/slack-refresh-team-settings "PostNL-Engineering" "https://postnl-engineering.slack.com/")
  (slack-start))
#+end_src

** Package
#+begin_src elisp
(use-package! slack
  :commands (slack-start)
  :hook ((slack-mode . visual-line-mode)
         (slack-buffer-mode . visual-line-mode))
  :init
  (advice-add 'slack-start :before #'my/slack-auto-refresh-wrapper) 
  :config
  (set-popup-rule! "^\\*slack" :ignore t)
  (setq slack-buffer-emojify t)
  (setq slack-prefer-current-team t)
  (evil-define-key 'normal slack-info-mode-map
    ",u" 'slack-room-update-messages)
  (evil-define-key 'normal slack-mode-map
    ",c" 'slack-buffer-kill
    ",ra" 'slack-message-add-reaction
    ",rr" 'slack-message-remove-reaction
    ",rs" 'slack-message-show-reaction-users
    ",pl" 'slack-room-pins-list
    ",pa" 'slack-message-pins-add
    ",pr" 'slack-message-pins-remove
    ",mm" 'slack-message-write-another-buffer
    ",me" 'slack-message-edit
    ",md" 'slack-message-delete
    ",u" 'slack-room-update-messages
    ",2" 'slack-message-embed-mention
    ",3" 'slack-message-embed-channel
    "\C-n" 'slack-buffer-goto-next-message
    "\C-p" 'slack-buffer-goto-prev-message)
  (evil-define-key 'normal slack-edit-message-mode-map
    ",k" 'slack-message-cancel-edit
    ",s" 'slack-message-send-from-buffer
    ",2" 'slack-message-embed-mention
    ",3" 'slack-message-embed-channel)
  (map! :leader
        (:prefix ("S" . "slack")
                 "t" #'my/slack-start
                 "S" #'slack-select-rooms
                 "u" #'slack-select-unread-rooms
                 "i" #'slack-im-select)))
#+end_src

#+begin_src elisp
(use-package! alert
  :config
  (setq alert-default-style 'libnotify))
#+end_src

#+begin_src elisp
(after! lui
  (setq lui-time-stamp-position 'right))
#+end_src

* Tidal Cycles
#+begin_src elisp
(use-package! tidal
  :custom
  (tidal-boot-script-path "~/Music/tidal/BootTidal.hs"))
#+end_src

* Music player
#+begin_src elisp
(use-package! emms
  :custom
  (emms-player-mpd-server-name "192.168.2.5")
  (emms-player-mpd-server-port "6600"))
#+end_src

#+begin_src elisp
(use-package! mpdel
  :custom
  (libmpdel-hostname "192.168.2.5") ; Replace with your server's IP if remote
  (libmpdel-port 6600)           ; Default MPD port
  )

#+end_src

* EWW
#+begin_src elisp
(set-popup-rule! "^\\*eww" :ignore t)
#+end_src

* Denote
#+begin_src elisp 
(use-package! denote
  :config
  ;; Set your main notes directory
  (setq denote-directory (expand-file-name "~/Documents/notes/"))
  
  ;; Default file extension is org, but you can also use md or txt
  (setq denote-file-type 'org) 
  
  ;; Configure prompts when running M-x denote
  (setq denote-prompts '(title keywords))
  
  ;; Optional: Pick a template format for Org front matter
  (setq denote-templates nil))

  
(map! :leader
    (:prefix-map ("n" . "notes")
                    (:prefix-map ("d" . "denote")
                    :desc "Create note"        "d" #'denote
                    :desc "Insert link"        "i" #'denote-link
                    :desc "Find/Create note"   "f" #'denote-open-or-create
                    :desc "Rename file"        "r" #'denote-rename-file)))
(after! org
  (require 'denote-org))
#+end_src

* tramp proxies
#+begin_src elisp
(after! tramp-mode
        (add-to-list 'tramp-default-proxies-alist
                     '("raspi" "\\`root\\'" "/ssh:raspi:")))
#+end_src
